# Generated by Django 4.1.5 on 2023-04-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_cream',
            field=models.ManyToManyField(blank=True, to='goods.cream'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_soap',
            field=models.ManyToManyField(blank=True, to='goods.soap'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_сandle',
            field=models.ManyToManyField(blank=True, to='goods.candle'),
        ),
    ]
