# Generated by Django 4.1.5 on 2023-03-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aroma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('summary', models.TextField(help_text='Enter a description of the aroma', max_length=100)),
                ('image', models.ImageField(blank=True, default='image-placeholder.png', upload_to='aroma/')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True, help_text="Enter manufacturer's address", max_length=50)),
                ('image', models.ImageField(blank=True, default='image-placeholder.png', upload_to='manufacturer/')),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('unit', models.TextField(help_text='Enter a description of the unit', max_length=20)),
            ],
        ),
    ]
